name: Lint and Deploy to Production
on:
  release:
    types: [published]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Yarn Deps
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install
      - run: make lint 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v1
      - name: Sync to S3 and Invalidate cloudfront
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: yarn install
      - run: yarn build
      - run: |
          export PATH=$PATH:`pwd`/node_modules/serverless/bin

          serverless syncToS3 --stage production
          serverless invalidateCloudFrontCache --stage production
          S3_FQDN=`serverless s3DomainInfo --stage production | awk '{print $4}'`
          echo "::set-output s3_fqdn=$S3_FQDN"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
  notify:
    name: notify
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          text: ${{ steps.deploy.outputs.s3_fqdn}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
